name = "fishing-app"
main = "index.py"
compatibility_date = "2026-04-27"

[[d1_databases]]
binding = "DB"
database_name = "d1-template-database"
database_id = "あなたのD1データベースID"

[assets]
directory = "."
